version: 2.1
orbs:
    node: circleci/node@3.0.1
    rsync: germade/rsync@0.0.1
jobs:
    deploy-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages
            - run:
                  command: npm run build
                  name: Building Nest project
            - run:
                  name: Deploy Over SSH
                  command: rsync --archive --verbose --progress . $SSH_USER@$SSH_HOST:~/www/obschak-api-test
workflows:
    deploy:
        jobs:
            - deploy-test:
                  type: approval
