version: 2.1
orbs:
    node: circleci/node@3.0.1
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages
            - run:
                  command: npm run build
                  name: Building Nest project
            - store_artifacts:
                  path: dist
    deploy:
        machine:
            enabled: true
        steps:
            - run:
                  name: Deploy Over SSH
                  command: |
                      ssh $SSH_USER@$SSH_HOST "pm2 list"
workflows:
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
